// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $AboutUs from "./routes/AboutUs.tsx";
import * as $Test from "./routes/Test.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_search from "./routes/api/search.ts";
import * as $index from "./routes/index.tsx";
import * as $shopping from "./routes/shopping.tsx";
import * as $AboutSeection from "./islands/AboutSeection.tsx";
import * as $FavoriteList from "./islands/FavoriteList.tsx";
import * as $InteractiveForm from "./islands/InteractiveForm.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $ProductFilterSidebar from "./islands/ProductFilterSidebar.tsx";
import * as $Recommendation from "./islands/Recommendation.tsx";
import * as $RecommendationSection from "./islands/RecommendationSection.tsx";
import * as $ShoppingSearch from "./islands/ShoppingSearch.tsx";
import * as $TestButton from "./islands/TestButton.tsx";
import * as $TipsSection from "./islands/TipsSection.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/AboutUs.tsx": $AboutUs,
    "./routes/Test.tsx": $Test,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/search.ts": $api_search,
    "./routes/index.tsx": $index,
    "./routes/shopping.tsx": $shopping,
  },
  islands: {
    "./islands/AboutSeection.tsx": $AboutSeection,
    "./islands/FavoriteList.tsx": $FavoriteList,
    "./islands/InteractiveForm.tsx": $InteractiveForm,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/ProductFilterSidebar.tsx": $ProductFilterSidebar,
    "./islands/Recommendation.tsx": $Recommendation,
    "./islands/RecommendationSection.tsx": $RecommendationSection,
    "./islands/ShoppingSearch.tsx": $ShoppingSearch,
    "./islands/TestButton.tsx": $TestButton,
    "./islands/TipsSection.tsx": $TipsSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
